.TH GENERATORRUNNER 1 "SEPTEMBER 2009" Linux "User Manuals"
.SH NAME
generatorrunner - plugin-based binding source code generator
.SH SYNOPSIS
.B generatorrunner \-\-generator-set=<plugin name> [options] header-file typesystem-file
.SH DESCRIPTION
.B generatorrunner
is a utility that uses the information taken from APIExtractor
related to the provided C++ headers and typesystem files and execute
generators using this information. Generators are plugins and you need
to specify one using the \-\-generator-set parameter. At the moment there
are two generators available:

.B qtdoc
\- Generates Sphinx-based documentation for C++ libraries documented using
.B qdoc3
documentation syntax, using the XML files created by the documentation tool
.B (qdoc3).
Can be called supplying
.B \-\-generator-set=qtdoc
to
.B generatorrunner
or by calling the convenience executable
.B docgenerator.

Other plugins can be used with
.B generatorrunner,
provided that they follow the generator front-end specifications,
and can be written to generate code or documentation for any target
languague you desire. For more information about the generator front-end
architecture and current limitations, refer to http://www.pyside.org/home-binding.

.SH OPTIONS
.SS "General options"
.IP \-\-api-version=<version>
Specify the supported api version used to generate the bindings.
.IP \-\-debug-level=[sparse|medium|full]
The amount of messages displayed.
.IP \-\-documentation-only
Only generates the documentation.
.IP \-\-drop-type-entries="<TypeEntry0>[;TypeEntry1;...]"
Semicolon separated list of type system entries (classes, namespaces, global functions and enums) to be dropped from generation.
.IP \-\-help \fR,\fP \-h \fR,\fP  -?
Prints the usage message.
.IP \-\-project-file=<file>
Text file containing a description of the binding project. Replaces and overrides command line arguments.
.IP \-\-include\-paths=\fI<path>[:path:..]\fR
The directories where the generator will search for the
headers. Works like gcc's \-I flag.
.IP \-\-license\-file=\fI[licensefile]\fR
Template for copyright headers of generated files.
.IP \-\-no\-supress\-warnings
Show all warnings.
.IP \-\-output\-directory=\fI[dir]\fR
The directory where the generated files will be written.
.IP \-\-silent
Avoid printing any messages.
.IP \-\-typesytem\-paths=\fI<path>[:path:..]\fR
The directories where the generator will search for the
external typesystems referred by the main one.
.IP \-\-version
Displays the current version.
Drops support for named args.
.SS "Specific to qtdoc plugin"
.IP \-\-documentation\-code\-snippets\-dir
Directory used to search code snippets used by the documentation
.IP \-\-documentation\-data\-dir
Directory with XML files generated by documentation tool (qdoc3 or Doxygen)
.IP \-\-documentation\-out\-dir
The directory where the generated documentation files will be written
.IP \-\-library\-source\-dir
Directory where library source code is located

.SH AUTHORS
Lauro Moura <lauro.neto at openbossa dot org>, Bruno Araujo <bruno.araujo at openbossa dot org>, Hugo Lima <hugo.lima at openbossa dot org>

