.TH PYSIDE\-RCC "1" "December 2010" "pyside\-rcc" "User Commands"
.SH NAME
pyside\-rcc \- PySide resource compiler
.SH DESCRIPTION
.SS "Usage:"
.IP
pyside\-rcc  [options] <inputs>
.SS "Options:"
.TP
\fB\-o\fR file
Write output to file rather than stdout
.TP
\fB\-py2\fR
Generate code for any Python v2.x version (default)
.TP
\fB\-py3\fR
Generate code for any Python v3.x version
.TP
\fB\-name\fR name
Create an external initialization function with name
.TP
\fB\-threshold\fR level
Threshold to consider compressing files
.TP
\fB\-compress\fR level
Compress input files by level
.TP
\fB\-root\fR path
Prefix resource access path with root path
.TP
\fB\-no\-compress
Disable all compression
.TP
\fB\-version
Display version
.TP
\fB\-help
Display this information
.SH COPYRIGHT
Copyright \(co 2010 Nokia Corporation and/or its subsidiary(\fB\-ies\fR)
.SH AUTHOR
.PP
This manpage was written by Marcelo Lira <marcelo@setantas.net>, on the 29. December 2010.
