.TH PYSIDE-LUPDATE "1" "December 2010" "pyside-lupdate" "User Commands"
.SH NAME
pyside\-lupdate \- extracts translatable messages from Qt UI files and Python source code.
.SH DESCRIPTION
.SS "Usage:"
.IP
pyside\-lupdate [options] project\-file
.IP
pyside\-lupdate [options] source\-files \-ts ts\-files
.SS "Options:"
.TP
\fB\-noobsolete
Drop all obsolete strings
.TP
\fB\-verbose
Explain what is being done
.TP
\fB\-version
Display the version of pyside-lupdate and exit
.TP
\fB\-help
Display this information and exit
.SH COPYRIGHT
Copyright \(co 2010 Nokia Corporation and/or its subsidiary(\fB\-ies\fR)
.SH AUTHOR
.PP
This manpage was written by Marcelo Lira <marcelo@setantas.net>, on the 29. December 2010.
